# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Site Settings
locale                   : "en-US"
title                    : "Mahdi"
title_separator          : "-"
name                     : &name "Dr Mahdi Maleki"
description              : &description "Privacy Researcher"

theme: jekyll-theme-cayman
