# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Site Settings
locale                   : "en-US"
title                    : "Mahdi"
title_separator          : "-"
name                     : &name "Dr Mahdi Maleki"
url: "https://MahdiMaleki.github.io"  # Your GitHub Pages URL
baseurl: ""  # Leave blank unless using a subdirectory
theme: jekyll-theme-cayman  # Pre-built theme for styling

# Navigation Links
header_pages:
  - index.md
  - about.md
