# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Site Settings
locale                   : "en-US"
title                    : "Mahdi"
title_separator          : "-"
name                     : &name "Dr Mahdi Maleki"
url: "https://MahdiMaleki.github.io/"  # Your GitHub Pages URL
baseurl: "skills-github-pages"  # Leave blank unless using a subdirectory
theme: jekyll-theme-cayman  # Pre-built theme for styling

# Navigation Links
header_pages:
  - index.md
  - about.md

plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Defaults for Pages and Posts
defaults:
  - scope:
      path: ""  # Apply to all files
    values:
      layout: default
      author_profile: true
      share: true

# Social Links
social:
  twitter: "https://twitter.com/YourTwitterHandle"
  linkedin: "https://linkedin.com/in/YourLinkedInProfile"
  github: "https://github.com/MahdiMaleki"

# Markdown Settings
markdown: kramdown
kramdown:
  input: GFM
  auto_ids: true

# SEO
seo:
  og_image: "/assets/images/og_image.png"  # Add Open Graph Image

# Plugins (Default GitHub Pages Plugins)
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Output Settings
permalink: /:title/  # Pretty URLs
paginate: 5  # Number of posts per page

# Include/Exclude Files
include:
  - assets
exclude:
  - README.md

